"""
Django settings for phonebook_django project.

Generated by 'django-admin startproject' using Django 3.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import logging
from pathlib import Path
import os
import ldap
from django_auth_ldap.config import LDAPSearch, LDAPSearchUnion
from django_auth_ldap.config import ActiveDirectoryGroupType
from django.core.mail import send_mail

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'rz4w+e(5194r97@izee&bf#e%ty2fe(n_u!n)xpy@_&hgq8vty'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'actionlog.apps.ActionlogConfig',
    'phonebook.apps.PhonebookConfig',
    'phonebook.templatetags',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'actionlog.middleware.ActionLogMiddleware',
]

ROOT_URLCONF = 'phonebook_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'actionlog.context_processors.proc_actionlog',
                'phonebook.context_processors.get_last_update',
            ],
        },
    },
]

WSGI_APPLICATION = 'phonebook_django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'phonebook_dev',
        'USER': 'dev',
        'PASSWORD': '321598753',
        'HOST': '10.63.40.4',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient"
        },
        "KEY_PREFIX": "phonebook"
    }
}

# Cache time to live is 15 minutes.
CACHE_TTL = 60 * 15


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'ru-RU'

TIME_ZONE = 'Europe/Samara'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_ROOT = os.path.abspath(os.path.join(BASE_DIR, '..', 'static'))
STATIC_URL = '/static/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

STATICFILES_DIRS = os.path.join(BASE_DIR, 'static'),

LOGIN_REDIRECT_URL = '/phonebook/'
LOGOUT_REDIRECT_URL = '/accounts/login'

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# ---------
# LDAP auth
# ---------

AUTH_LDAP_SERVER_URI = "ldap://dc2.gk.local"
AUTH_LDAP_BIND_DN = "cn=ldap-bot,ou=IT,dc=gk,dc=local"
AUTH_LDAP_BIND_PASSWORD = "12345678"
AUTH_LDAP_USER_SEARCH = LDAPSearchUnion(
            LDAPSearch("ou=IT,dc=gk,dc=local", ldap.SCOPE_SUBTREE, "sAMAccountName=%(user)s"),
            LDAPSearch("ou=ABZ,dc=gk,dc=local", ldap.SCOPE_SUBTREE, "sAMAccountName=%(user)s"),
            )

AUTH_LDAP_USER_ATTR_MAP = {
            "first_name": "givenName",
            "last_name": "sn",
            "email": "mail",
}

AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
            "ou=Users,dc=gk,dc=local", ldap.SCOPE_SUBTREE, "(objectCategory=Group)"
            )

AUTH_LDAP_GROUP_TYPE = ActiveDirectoryGroupType(name_attr="cn")

AUTH_LDAP_USER_FLAGS_BY_GROUP = {
            "is_active": "cn=PhonebookUsers,cn=Users,dc=gk,dc=local",
            "is_superuser": "cn=IT,cn=Users,dc=gk,dc=local",
            "is_staff": "cn=PhonebookStaff,cn=Users,dc=gk,dc=local",
            }

AUTH_LDAP_FIND_GROUP_PERMS = True
AUTH_LDAP_ALWAYS_UPDATE_USER = True
# AUTH_LDAP_CACHE_GROUPS = True
# AUTH_LDAP_GROUP_CACHE_TIMEOUT = 1  # 1 hour cache

AUTHENTICATION_BACKENDS = [
            'django_auth_ldap.backend.LDAPBackend',
            'django.contrib.auth.backends.ModelBackend',
]

# EMAIL_USE_SSL = True
# EMAIL_HOST = 'smtp.yandex.ru'
# EMAIL_PORT = 465
# EMAIL_HOST_USER = 'it@avsst.ru'
# EMAIL_HOST_PASSWORD = 'sngntjwudptztzop'
# RECIPIENT_LIST = ['filippov@avsst.ru', 'dok@abz1.ru']

EMAIL_USE_SSL = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = os.environ.get('EMAIL_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_PASSWORD')
RECIPIENT_LIST = ['filippov@avsst.ru', 'dok@abz1.ru']

LAST_UPDATE = '27.05.2021'
