# Generated by Django 3.1.4 on 2021-05-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionlog',
            old_name='http_referer',
            new_name='path',
        ),
        migrations.RenameField(
            model_name='actionlog',
            old_name='user',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='ipaddress',
            field=models.GenericIPAddressField(db_index=True, protocol='ipv4'),
        ),
    ]
