# Generated by Django 3.1.4 on 2021-05-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
