# Generated by Django 3.2 on 2021-05-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='user',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
