# Generated by Django 3.2 on 2021-05-20 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionlog', '0002_auto_20210517_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
