# Generated by Django 3.1.7 on 2021-05-23 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='Компания')),
                ('slug', models.SlugField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('givenName', models.CharField(max_length=255, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('displayName', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='ФИО')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('department', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отдел')),
                ('physicalDeliveryOfficeName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Местоположение')),
                ('mail', models.CharField(blank=True, max_length=255, null=True, verbose_name='Почта')),
                ('telephoneNumber', models.CharField(blank=True, max_length=4, null=True, verbose_name='Внутренний')),
                ('mobile', models.CharField(blank=True, max_length=15, null=True, verbose_name='Мобильный')),
                ('company', models.CharField(default=None, max_length=255, verbose_name='Компания')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
    ]
