# Generated by Django 3.2 on 2021-05-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='displayName',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='ФИО'),
        ),
    ]
