# Generated by Django 3.1.4 on 2021-05-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0002_auto_20210511_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitlog',
            name='hostname',
            field=models.CharField(default='unknown', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='visitlog',
            name='username',
            field=models.CharField(default='unknown', max_length=255, null=True),
        ),
    ]
