# Generated by Django 3.1.4 on 2021-05-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0003_auto_20210511_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitlog',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
