# Generated by Django 3.1.7 on 2021-05-12 05:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0004_auto_20210511_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitlog',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
