# Generated by Django 3.2 on 2021-05-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0005_auto_20210512_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitlog',
            name='hostname',
        ),
        migrations.RemoveField(
            model_name='visitlog',
            name='username',
        ),
        migrations.AddField(
            model_name='visitlog',
            name='http_referer',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
