# Generated by Django 3.2 on 2021-05-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0006_auto_20210512_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitlog',
            name='hostname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
