# Generated by Django 3.2 on 2021-05-14 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0007_visitlog_hostname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitLog',
        ),
    ]
